In [4]:
import numpy as np 

In [5]:
python_list = [1, 2, 3, 4, 5]
print(python_list)
print(type(python_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
python_2d_array = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
print(python_2d_array)
print(type(python_2d_array))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
<class 'list'>


In [9]:
numpy_2d_array = np.array(python_2d_array)
print(numpy_2d_array)
print(type(numpy_2d_array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [12]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [14]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(15).reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5)

array([0.14674641, 0.50999932, 0.88504755, 0.09227566, 0.90685008])

In [22]:
np.random.randn(5)

array([ 1.20774115,  0.26173422, -0.1422607 , -1.70707398, -0.83163605])

In [23]:
np.random.randint(1,70)

26

In [24]:
np.random.randint(0,95,10)

array([37, 17, 84, 85,  5, 35,  0, 90, 12, 13])

In [25]:
S=np.random.randint(0,100,20).reshape(4,5)
S

array([[11, 10, 21, 32, 39],
       [86, 18, 45, 44, 20],
       [88,  5, 33, 10, 56],
       [23, 84, 34, 64, 50]])

In [28]:
print(f'The smallest value in S is {S.min()} , and is located at position {S.argmin()}')
print(f'The largest value in S is {S.max()} , and is located at position {S.argmax()}')

The smallest value in S is 5 , and is located at position 11
The largest value in S is 88 , and is located at position 10


In [29]:
S.shape

(4, 5)

In [30]:
np.shape(S)

(4, 5)

In [31]:
A = np.arange(1, 16)
B = np.arange(1, 30, 2)
C = np.arange(0,4).reshape(2,2)
D = np.arange(0,4).reshape(2,2)
E = np.arange(1,16).reshape(3,5)
F = np.arange(11)
print(f' A: {A}')
print(f' B: {B}')
print('C:')
print(C)
print('D:')
print(D)
print('E:')
print(E)
print(f'F: {F}')

 A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 B: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]
C:
[[0 1]
 [2 3]]
D:
[[0 1]
 [2 3]]
E:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F: [ 0  1  2  3  4  5  6  7  8  9 10]


In [32]:
A+B

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [33]:
A+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
A-B

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14])

In [35]:
A-5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
A*B

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231, 276, 325,
       378, 435])

In [37]:
A*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [38]:
A/B

array([1.        , 0.66666667, 0.6       , 0.57142857, 0.55555556,
       0.54545455, 0.53846154, 0.53333333, 0.52941176, 0.52631579,
       0.52380952, 0.52173913, 0.52      , 0.51851852, 0.51724138])

In [39]:
A/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5])

In [40]:
np.matmul(C,D)

array([[ 2,  3],
       [ 6, 11]])

In [41]:
np.sqrt(E)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [42]:
np.log(D)

<ipython-input-42-d1fd0535efec>:1: RuntimeWarning: divide by zero encountered in log
  np.log(D)


array([[      -inf, 0.        ],
       [0.69314718, 1.09861229]])

In [43]:
np.log(E)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [44]:
np.where(F%2==0,-1,F*100)

array([ -1, 100,  -1, 300,  -1, 500,  -1, 700,  -1, 900,  -1])

In [45]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
print(f'A[0]: {A[0]}')
print(f'A[5]: {A[5]}')
print(f'A[0]: {A[14]}')

A[0]: 0
A[5]: 5
A[0]: 14


In [47]:
A[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
A[0:10]=500
A

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14])

In [49]:
B=np.arange(50).reshape(5,10)
B


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
print(f'0th row and 2nd col in B: {B[0,2]}')
print(f'3th row and 3nd col in B: {B[3,3]}')
print(f'4th row and 2nd col in B: {B[4,2]}')

0th row and 2nd col in B: 2
3th row and 3nd col in B: 33
4th row and 2nd col in B: 42


In [51]:
B[0:2,3:5]

array([[ 3,  4],
       [13, 14]])

In [52]:
B[0:2, 3:5]=-1
B

array([[ 0,  1,  2, -1, -1,  5,  6,  7,  8,  9],
       [10, 11, 12, -1, -1, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
C=np.arange(50).reshape(10,5)
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [54]:
C%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [55]:
(C%2==0).sum()

25

In [56]:
C[C%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [ ]:
new 